# Generated by Django 2.2.1 on 2022-11-24 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ID No. ')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Name: ')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='idp/img', verbose_name='Profile Pic.')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True, verbose_name='Sex: ')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('male_hhs', models.PositiveIntegerField(null=True, verbose_name='Male HH Size')),
                ('female_hhs', models.PositiveIntegerField(null=True, verbose_name='Female HH Size')),
                ('total_hhs', models.PositiveIntegerField(null=True, verbose_name='Tota HH Size')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone No. ')),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=20, null=True, verbose_name='Marital Status')),
                ('region', models.CharField(choices=[('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromiya', 'Oromiya'), ('Addis Ababa', 'Addis Ababa'), ('Somalia', 'Somalia'), ('SNNP', 'SNNP'), ('Gambela', 'Gambela'), ('Benshangul', 'Benshangul'), ('Diredawa', 'Diredawa'), ('Harar', 'Harar'), ('Sidama', 'Sidama')], max_length=20, verbose_name='Prev. Region')),
                ('ozone', models.CharField(choices=[('Central', 'Central'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('North Western', 'North Western'), ('Southern', 'Southern'), ('South Eastern', 'South Eastern'), ('Out of Tigray', 'Out of Tigray')], max_length=20, verbose_name='Prev. Zone')),
                ('owereda', models.CharField(choices=[('Out of Tigray', 'Out of Tigray'), ('Abergele', 'Abergele'), ('Abi Adi', 'Abi Adi'), ('Adet', 'Adet'), ('Adwa', 'Adwa'), ('Ahferom', 'Ahferom'), ('Ahsea', 'Ahsea'), ('Axum', 'Axum'), ('Chila', 'Chila'), ('Edaga Arbi', 'Edaga Arbi'), ('Egela', 'Egela'), ('Embaseneyti', 'Embaseneyti'), ('Endafelasi', 'Endafelasi'), ('Enticho', 'Enticho'), ('Hahayle', 'Hahayle'), ('Kola Tembien', 'Kola Tembien'), ('Laelay Maychew', 'Laelay Maychew'), ('Naeder', 'Naeder'), ('Qeyih Tekli', 'Qeyih Tekli'), ('Rama', 'Rama'), ('Rama Adi Arbaete', 'Rama Adi Arbaete'), ('Tahtay Maychew', 'Tahtay Maychew'), ('Tanqua Milash', 'Tanqua Milash'), ('Adigrat', 'Adigrat'), ('Atsbi', 'Atsbi'), ('Atsbi Endaselasie', 'Atsbi Endaselasie'), ('Bizet', 'Bizet'), ('Edaga Hamus', 'Edaga Hamus'), ('Erob', 'Erob'), ('Freweyni', 'Freweyni'), ('Ganta Afeshum', 'Ganta Afeshum'), ('Gerealta', 'Gerealta'), ('Golomekeda', 'Golomekeda'), ('Hawzien', 'Hawzien'), ('Kilte Awlaelo', 'Kilte Awlaelo'), ('Saesie Tsaeda Emba', 'Saesie Tsaeda Emba'), ('Tsrae Wemberta', 'Tsrae Wemberta'), ('Wukro', 'Wukro'), ('Zalambesa', 'Zalambesa'), ('Adigudem', 'Adigudem'), ('Dogua Tembien', 'Dogua Tembien'), ('Enderta', 'Enderta'), ('Hagere Selam', 'Hagere Selam'), ('Hintalo', 'Hintalo'), ('Seharti', 'Seharti'), ('Samre', 'Samre'), ('Wajerat', 'Wajerat'), ('Alamata', 'Alamata'), ('Bora', 'Bora'), ('Chercher', 'Chercher'), ('Emba Alaje', 'Emba Alaje'), ('Enda Mokoni', 'Enda Mokoni'), ('Korem', 'Korem'), ('Maychew', 'Maychew'), ('Mokoni', 'Mokoni'), ('Ofla', 'Ofla'), ('Raya Alamata', 'Raya Alamata'), ('Raya Azebo', 'Raya Azebo'), ('Selewa', 'Selewa'), ('Adi Daero', 'Adi Daero'), ('Asgede', 'Asgede'), ('Endabaguna', 'Endabaguna'), ('Laelay Qoraro', 'Laelay Qoraro'), ('Laelay Tselemti', 'Laelay Tselemti'), ('Maekelay Adyabo', 'Maekelay Adyabo'), ('May Tsebri', 'May Tsebri'), ('Seyemti Adyabo', 'Seyemti Adyabo'), ('Sheraro', 'Sheraro'), ('Shire Endaselasie', 'Shire Endaselasie'), ('Tahtay Adyabo', 'Tahtay Adyabo'), ('Tahtay Qoraro', 'Tahtay Qoraro'), ('Tselemti', 'Tselemti'), ('Tsimbla', 'Tsimbla'), ('Zana', 'Zana'), ('Awra', 'Awra'), ('Dansha', 'Dansha'), ('Kafta Humera', 'Kafta Humera'), ('May Cadra', 'May Cadra'), ('May Gaba', 'May Gaba'), ('Qorarit', 'Qorarit'), ('Setit Humera', 'Setit Humera'), ('Tsegede', 'Tsegede'), ('Welkayit', 'Welkayit')], max_length=20, verbose_name='Prev. Woreda')),
                ('okebele', models.CharField(max_length=20, verbose_name='Prev. Kebele')),
                ('czone', models.CharField(choices=[('Mekelle', 'Mekelle')], max_length=20, verbose_name='Current Zone')),
                ('cwereda', models.CharField(choices=[('Adi Haqi', 'Adi Haqi'), ('Ayder', 'Ayder'), ('Hadinet', 'Hadinet'), ('Hawelti', 'Hawelti'), ('Kedamay Woyane', 'Kedamay Woyane'), ('Quiha', 'Quiha'), ('Semien', 'Semien')], max_length=20, verbose_name='Current Subcity')),
                ('ckebele', models.CharField(blank=True, choices=[('Amora', 'Amora'), ('Debre Genet', 'Debre Genet'), ('Hayelom', 'Hayelom'), ('Hidase', 'Hidase'), ('Tsinat Woyane', 'Tsinat Woyane'), ('Adiha', 'Adiha'), ('Ginbot 20', 'Ginbot 20'), ('Maryam Dihan', 'Maryam Dihan'), ('Marta', 'Marta'), ('Sertse', 'Sertse'), ('Asmelash', 'Asmelash'), ('Aynalem', 'Aynalem'), ('Debri', 'Debri'), ('Hidase', 'Hidase'), ('Metkel', 'Metkel'), ('Simret', 'Simret'), ('Werie', 'Werie'), ('Adi Shumdhein', 'Adi Shumdhein'), ('Hayelom', 'Hayelom'), ('Hidas', 'Hidas'), ('Mommona', 'Mommona'), ('Selam', 'Selam'), ('Harya', 'Harya'), ('Selam', 'Selam'), ('Walta', 'Walta'), ('Zeslasie', 'Zeslasie'), ('Abreha', 'Abreha'), ('Asmelash', 'Asmelash'), ('May Tsedo', 'May Tsedo'), ('Shibta', 'Shibta'), ('Dedebit', 'Dedebit'), ('Endustry', 'Endustry'), ('Meles', 'Meles'), ('Mesfin', 'Mesfin'), ('Yekatit', 'Yekatit')], max_length=20, null=True, verbose_name='Current Subcity')),
                ('idp_site', models.CharField(max_length=20, verbose_name='IDP Site')),
                ('year_fled', models.PositiveIntegerField(null=True, verbose_name='Year Fled')),
                ('plw', models.BooleanField(default=False, verbose_name='Pregnant or Lactating')),
                ('is_idp', models.BooleanField(default=False, verbose_name='Is IDP?')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disabled?')),
                ('psnp_beneficiary', models.BooleanField(default=False, verbose_name='PSNP Beneficiary')),
                ('emergency_relief_host', models.BooleanField(default=False, verbose_name='Emergency Relief Host')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_head', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_head', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('profilepic', models.ImageField(blank=True, upload_to='idp/img', verbose_name='Profile Pic.')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, verbose_name='Sex: ')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=15, verbose_name='Marital Status')),
                ('relation', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Relative', 'Relative'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20)),
                ('credence', models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Vaccine Certificate', 'Vaccine Certificate'), ('Marriage Certificate', 'Marriage Certificate'), ('Social Justice Certificate', 'Social Just Certificate'), ('Medical Certificate', 'Medical Certificate'), ('Other', 'Other')], max_length=50)),
                ('credence_pic', models.ImageField(blank=True, upload_to='idp/img')),
                ('plw', models.BooleanField(default=False, verbose_name='Pregnant or Lactating')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disabled?')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_member', to=settings.AUTH_USER_MODEL)),
                ('family_head', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='idp.FamilyHead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='Duplicates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True, verbose_name='Sex: ')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Age')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone No. ')),
                ('region', models.CharField(choices=[('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromiya', 'Oromiya'), ('Addis Ababa', 'Addis Ababa'), ('Somalia', 'Somalia'), ('SNNP', 'SNNP'), ('Gambela', 'Gambela'), ('Benshangul', 'Benshangul'), ('Diredawa', 'Diredawa'), ('Harar', 'Harar'), ('Sidama', 'Sidama')], max_length=15, verbose_name='Prev. Region')),
                ('ozone', models.CharField(choices=[('Central', 'Central'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('North Western', 'North Western'), ('Southern', 'Southern'), ('South Eastern', 'South Eastern'), ('Out of Tigray', 'Out of Tigray')], max_length=15, verbose_name='Prev. Zone')),
                ('owereda', models.CharField(choices=[('Out of Tigray', 'Out of Tigray'), ('Abergele', 'Abergele'), ('Abi Adi', 'Abi Adi'), ('Adet', 'Adet'), ('Adwa', 'Adwa'), ('Ahferom', 'Ahferom'), ('Ahsea', 'Ahsea'), ('Axum', 'Axum'), ('Chila', 'Chila'), ('Edaga Arbi', 'Edaga Arbi'), ('Egela', 'Egela'), ('Embaseneyti', 'Embaseneyti'), ('Endafelasi', 'Endafelasi'), ('Enticho', 'Enticho'), ('Hahayle', 'Hahayle'), ('Kola Tembien', 'Kola Tembien'), ('Laelay Maychew', 'Laelay Maychew'), ('Naeder', 'Naeder'), ('Qeyih Tekli', 'Qeyih Tekli'), ('Rama', 'Rama'), ('Rama Adi Arbaete', 'Rama Adi Arbaete'), ('Tahtay Maychew', 'Tahtay Maychew'), ('Tanqua Milash', 'Tanqua Milash'), ('Adigrat', 'Adigrat'), ('Atsbi', 'Atsbi'), ('Atsbi Endaselasie', 'Atsbi Endaselasie'), ('Bizet', 'Bizet'), ('Edaga Hamus', 'Edaga Hamus'), ('Erob', 'Erob'), ('Freweyni', 'Freweyni'), ('Ganta Afeshum', 'Ganta Afeshum'), ('Gerealta', 'Gerealta'), ('Golomekeda', 'Golomekeda'), ('Hawzien', 'Hawzien'), ('Kilte Awlaelo', 'Kilte Awlaelo'), ('Saesie Tsaeda Emba', 'Saesie Tsaeda Emba'), ('Tsrae Wemberta', 'Tsrae Wemberta'), ('Wukro', 'Wukro'), ('Zalambesa', 'Zalambesa'), ('Adigudem', 'Adigudem'), ('Dogua Tembien', 'Dogua Tembien'), ('Enderta', 'Enderta'), ('Hagere Selam', 'Hagere Selam'), ('Hintalo', 'Hintalo'), ('Seharti', 'Seharti'), ('Samre', 'Samre'), ('Wajerat', 'Wajerat'), ('Alamata', 'Alamata'), ('Bora', 'Bora'), ('Chercher', 'Chercher'), ('Emba Alaje', 'Emba Alaje'), ('Enda Mokoni', 'Enda Mokoni'), ('Korem', 'Korem'), ('Maychew', 'Maychew'), ('Mokoni', 'Mokoni'), ('Ofla', 'Ofla'), ('Raya Alamata', 'Raya Alamata'), ('Raya Azebo', 'Raya Azebo'), ('Selewa', 'Selewa'), ('Adi Daero', 'Adi Daero'), ('Asgede', 'Asgede'), ('Endabaguna', 'Endabaguna'), ('Laelay Qoraro', 'Laelay Qoraro'), ('Laelay Tselemti', 'Laelay Tselemti'), ('Maekelay Adyabo', 'Maekelay Adyabo'), ('May Tsebri', 'May Tsebri'), ('Seyemti Adyabo', 'Seyemti Adyabo'), ('Sheraro', 'Sheraro'), ('Shire Endaselasie', 'Shire Endaselasie'), ('Tahtay Adyabo', 'Tahtay Adyabo'), ('Tahtay Qoraro', 'Tahtay Qoraro'), ('Tselemti', 'Tselemti'), ('Tsimbla', 'Tsimbla'), ('Zana', 'Zana'), ('Awra', 'Awra'), ('Dansha', 'Dansha'), ('Kafta Humera', 'Kafta Humera'), ('May Cadra', 'May Cadra'), ('May Gaba', 'May Gaba'), ('Qorarit', 'Qorarit'), ('Setit Humera', 'Setit Humera'), ('Tsegede', 'Tsegede'), ('Welkayit', 'Welkayit')], max_length=15, verbose_name='Prev. Woreda')),
                ('okebele', models.CharField(max_length=10, verbose_name='Prev. Kebele')),
                ('czone', models.CharField(choices=[('Mekelle', 'Mekelle')], max_length=15, verbose_name='Current Zone')),
                ('cwereda', models.CharField(choices=[('Adi Haqi', 'Adi Haqi'), ('Ayder', 'Ayder'), ('Hadinet', 'Hadinet'), ('Hawelti', 'Hawelti'), ('Kedamay Woyane', 'Kedamay Woyane'), ('Quiha', 'Quiha'), ('Semien', 'Semien')], max_length=15, verbose_name='Current Subcity')),
                ('ckebele', models.CharField(choices=[('Amora', 'Amora'), ('Debre Genet', 'Debre Genet'), ('Hayelom', 'Hayelom'), ('Hidase', 'Hidase'), ('Tsinat Woyane', 'Tsinat Woyane'), ('Adiha', 'Adiha'), ('Ginbot 20', 'Ginbot 20'), ('Maryam Dihan', 'Maryam Dihan'), ('Marta', 'Marta'), ('Sertse', 'Sertse'), ('Asmelash', 'Asmelash'), ('Aynalem', 'Aynalem'), ('Debri', 'Debri'), ('Hidase', 'Hidase'), ('Metkel', 'Metkel'), ('Simret', 'Simret'), ('Werie', 'Werie'), ('Adi Shumdhein', 'Adi Shumdhein'), ('Hayelom', 'Hayelom'), ('Hidas', 'Hidas'), ('Mommona', 'Mommona'), ('Selam', 'Selam'), ('Harya', 'Harya'), ('Selam', 'Selam'), ('Walta', 'Walta'), ('Zeslasie', 'Zeslasie'), ('Abreha', 'Abreha'), ('Asmelash', 'Asmelash'), ('May Tsedo', 'May Tsedo'), ('Shibta', 'Shibta'), ('Dedebit', 'Dedebit'), ('Endustry', 'Endustry'), ('Meles', 'Meles'), ('Mesfin', 'Mesfin'), ('Yekatit', 'Yekatit')], max_length=15, verbose_name='Current Tabyas/Kebeles')),
                ('idp_site', models.CharField(max_length=20, verbose_name='IDP Site')),
                ('cleared', models.BooleanField(default=False, verbose_name='Pregnant or Lactating')),
                ('discovered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('household_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='head_duplicaes', to='idp.FamilyHead')),
            ],
        ),
    ]
